public class MethodOfSuDivisionMultSub {
    
    public integer sum(integer a,integer b)
    {
        integer c = a+b;
        return c;
    }
    public integer sub(integer a,integer b)
    {
        integer c = a-b;
        return c;
    }
    public integer div(integer a,integer b)
    {
        integer c=a/b;
        return c;
    }
    public integer mult(integer a,integer b)
    {
        integer c = a*b;
        return c;
    }

}